### ISSUE TITLE
Build failures on Linux

### ISSUE THREAD

**Issue by fusion809** [MustaphaTR/sole-survivor#5]
Hi,

I know the Travis log clearly shows that this mod isn't successfully building on Linux and hasn't been for months, but in case you haven't been looking at the Travis logs I thought I'd share this fact. Presently for me the build failure is:

```bash
make[1]: Entering directory '/data/GitHub/others/sole-survivor/engine'
CSC fixheader.exe
error CS0006: Metadata file 'thirdparty/download/ICSharpCode.SharpZipLib.dll' could not be found
error CS0006: Metadata file 'thirdparty/download/FuzzyLogicLibrary.dll' could not be found
error CS0006: Metadata file 'thirdparty/download/MaxMind.Db.dll' could not be found
error CS0006: Metadata file 'thirdparty/download/Eluant.dll' could not be found
error CS0006: Metadata file 'thirdparty/download/rix0rrr.BeaconLib.dll' could not be found
make[1]: *** [Makefile:273: fixheader.exe] Error 1
```

If you are fully aware and simply haven't found a way to fix it or w/e, feel free to ignore this, but I thought I'd alert ye to this, in case you weren't aware.

Thanks for your time

**Comment by MustaphaTR** [comment]
This should be fixed because of the engine updates done since. Also travis passes, so it probably does.
