### ISSUE TITLE
Desert maps crashes the game and quitting during a match crashes the game.

### ISSUE THREAD

**Issue by MikillRosen** [MustaphaTR/sole-survivor#9]
Desert map crash: [exception-2019-12-18T005919Z.log](https://github.com/MustaphaTR/sole-survivor/files/3976152/exception-2019-12-18T005919Z.log)

Quit game crash: [exception-2019-12-18T010007Z.log](https://github.com/MustaphaTR/sole-survivor/files/3976153/exception-2019-12-18T010007Z.log)

[desert map crash graphics.log](https://github.com/MustaphaTR/sole-survivor/files/3976156/desert.map.crash.graphics.log)

[quit game crash graphics.log](https://github.com/MustaphaTR/sole-survivor/files/3976158/quit.game.crash.graphics.log)

**Comment by MustaphaTR** [comment]
Seems to be related to this issue at upstream: https://github.com/OpenRA/OpenRA/issues/17087#issuecomment-566766351
If last comment is to be belived, i think doing an engine update to this mod should fix it.

**Comment by MustaphaTR** [comment]
This should be fixed already.
